services:
  postgres:
    image: postgres:15-alpine
    container_name: investapp-postgres
    environment:
      POSTGRES_DB: investapp
      POSTGRES_USER: investapp
      POSTGRES_PASSWORD: investapp
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U investapp -d investapp"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: investapp-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: investapp-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: investapp
      RABBITMQ_DEFAULT_PASS: investapp
    ports:
      - "5672:5672"
      - "15672:15672" # UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: investapp-api
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/investapp
      SPRING_DATASOURCE_USERNAME: investapp
      SPRING_DATASOURCE_PASSWORD: investapp
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: "6379"
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: "5672"
      SPRING_RABBITMQ_USERNAME: investapp
      SPRING_RABBITMQ_PASSWORD: investapp
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  pgdata:
  redisdata:
